import puppeteer from 'puppeteer';

const BRANDING_STYLES = `
    body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
        color: #1f2937;
        line-height: 1.6;
        margin: 0;
        padding: 40px;
        background-color: #ffffff;
    }
    h1, h2, h3 {
        color: #111827;
        margin-top: 24px;
        margin-bottom: 16px;
    }
    h1 { font-size: 24px; border-bottom: 2px solid #4F46E5; padding-bottom: 8px; }
    h2 { font-size: 20px; color: #4F46E5; }
    h3 { font-size: 16px; color: #374151; }
    p { margin-bottom: 16px; }
    .card {
        background-color: #f9fafb;
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 16px;
        margin-bottom: 16px;
        break-inside: avoid;
    }
    .term { font-weight: bold; color: #4F46E5; }
    .footer {
        margin-top: 40px;
        text-align: center;
        font-size: 12px;
        color: #6b7280;
        border-top: 1px solid #e5e7eb;
        padding-top: 16px;
    }
`;

export async function generatePdf(htmlContent: string): Promise<Buffer> {
    const fullHtml = `
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>${BRANDING_STYLES}</style>
        </head>
        <body>
            ${htmlContent}
            <div class="footer">Generated by AI Study Assistant</div>
        </body>
        </html>
    `;

    const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    });

    try {
        const page = await browser.newPage();
        await page.setContent(fullHtml, { waitUntil: 'domcontentloaded' });

        const pdfBuffer = await page.pdf({
            format: 'A4',
            margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' },
            printBackground: true
        });

        return Buffer.from(pdfBuffer);
    } finally {
        await browser.close();
    }
}
